apiVersion: v2
appVersion: "1.0"
description: A Helm chart for rd-location-ref-api
name: rd-location-ref-api
home: https://github.com/hmcts/rd-location-ref-api
version: 0.0.11
maintainers:
  - name: Reference Data Team
dependencies:
  - name: java
    version: ~3.4.4
    repository: '@hmctspublic'
