java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    POSTGRES_PORT: "{{ .Values.postgresql.postgresqlPort}}"
    LOCATIONS_DB: classpath:db/migration,classpath:db/postgres,classpath:db/migrationAks
    LAUNCH_DARKLY_ENV: "preview"
  postgresql:
    enabled: true
    postgresqlUsername: dbrdlocationref
    postgresqlPassword: dbrdlocationref
    postgresqlDatabase: dbrdlocationref
    postgresqlPort: 5432
  keyVaults:
    rd:
      secrets:
        - ApplicationInsightsInstrumentationKey
        - LD-SDK-KEY
        - location-ref-api-s2s-secret